PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "RETAILER" (
    "RETAILER_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "NAME" TEXT NOT NULL,
    "TYPE" TEXT,
    "CITY" TEXT,
    "STATE" TEXT,
    "COUNTRY" TEXT,
    "SHIPPING_COST" REAL,
    "ADDITIONAL_COST" REAL
);
CREATE TABLE "PRODUCER" (
    "PRODUCER_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "NAME" TEXT NOT NULL
);
CREATE TABLE "DISTILLERY" (
    "DISTILLERY_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "NAME" TEXT NOT NULL,
    "REGION" TEXT
);
CREATE TABLE "SCOTCH" (
    "SCOTCH_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "PRODUCER" INTEGER,
    "DISTILLERY" INTEGER,
    "NAME" TEXT,
    "AGE" INTEGER
);
CREATE TABLE "PRICE" (
    "PRICE_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "RETAILER_ID" INTEGER NOT NULL,
    "SCOTCH_ID" INTEGER NOT NULL,
    "PRICE" REAL
);
COMMIT;
